include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer: 
  plugins:
    - dart_code_metrics
  exclude: 
    - "**/*gj.dart"
    - "**/*gr.dart"
    - "**/*freezed.dart"


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
